export default db = {
    "GCLOUD_PROJECT": "[YOUR_PROJECT_ID]",
    "DATA_BACKEND": "cloudsql",
    "MYSQL_USER": "[YOUR_MYSQL_USERNAME]",
    "MYSQL_PASSWORD": "[YOUR_MYSQL_PASSWORD]",
    "INSTANCE_CONNECTION_NAME": "[YOUR_INSTANCE_CONNECTION_NAME]"
  }